name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, ubuntu-latest, macos-13, macos-13, macos-13]
    timeout-minutes: 360
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  echo 'LINUX'
                  sleep 60
             else
                  echo 'MACOS'
                  sleep 60
             fi
        shell: bash
